version: '3.8'

networks:
  ksqldbnetwork:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    networks: 
      - ksqldbnetwork
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker01:
    image: 'bitnami/kafka:latest'
    ports:
      - '29092:29092'
    networks: 
      - ksqldbnetwork
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://broker01:9092,EXTERNAL://broker01:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker01:9092,EXTERNAL://localhost:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  #    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:3.30.0
    depends_on:
      - broker01
    ports:
      - "9000:9000"
    networks: 
      - ksqldbnetwork
    environment:
      - KAFKA_BROKERCONNECT=broker01:9092
      - JVM_OPTS=-Xms32M -Xms64M
      - SERVER_SERVLET_CONTEXTPATH=/
            
  connect:
    image: debezium/connect:2.0
    ports:
     - 8083:8083
    networks: 
      - ksqldbnetwork
    links:
     - broker01
    environment:
     - BOOTSTRAP_SERVERS=broker01:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses

  ksqldb-server:
    image: confluentinc/ksqldb-server:${KSQLDB_VERSION}
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker01
      - connect
    ports:
      - "8088:8088"
    networks: 
      - ksqldbnetwork
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "broker01:9092"
      KSQL_HOST_NAME: ksqldb-server      
      KSQL_KSQL_CONNECT_URL: "http://connect:8083"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0


  ksqldb-cli:
    image: confluentinc/ksqldb-cli:${KSQLDB_VERSION}
    depends_on:
      - broker01
      - ksqldb-server
    networks: 
      - ksqldbnetwork
    entrypoint: /bin/sh
    tty: true
